CREATE TABLE api.ai_dispute_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shift_id uuid NOT NULL,
  disputed_by uuid NOT NULL,
  dispute_type text CHECK (dispute_type = ANY (ARRAY['no_show'::text, 'late'::text, 'gps'::text, 'rating'::text, 'pay'::text])),
  evidence jsonb NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'under_review'::text, 'resolved'::text, 'escalated'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_dispute_cases_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_dispute_shift FOREIGN KEY (shift_id) REFERENCES api.shifts(shift_id),
  CONSTRAINT fk_ai_dispute_user FOREIGN KEY (disputed_by) REFERENCES api.users(id)
);
CREATE TABLE api.ai_dispute_verdicts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dispute_id uuid NOT NULL UNIQUE,
  grok_raw_response jsonb NOT NULL,
  verdict text,
  confidence numeric,
  explanation text,
  recommended_action text,
  cost_usd numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_dispute_verdicts_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_verdict_dispute FOREIGN KEY (dispute_id) REFERENCES api.ai_dispute_cases(id)
);
CREATE TABLE api.ai_grok_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  feature text NOT NULL,
  model text DEFAULT 'grok-4'::text,
  prompt_tokens integer,
  completion_tokens integer,
  total_tokens integer,
  cost_usd numeric,
  raw_request jsonb NOT NULL,
  raw_response jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_grok_requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_grok_user FOREIGN KEY (user_id) REFERENCES api.users(id)
);
CREATE TABLE api.ai_recommendations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid NOT NULL,
  shift_id uuid NOT NULL,
  recommendation_type text,
  title text,
  body text,
  priority integer DEFAULT 3,
  expires_at timestamp with time zone,
  seen boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_rec_worker FOREIGN KEY (worker_id) REFERENCES api.workers(worker_id),
  CONSTRAINT fk_ai_rec_shift FOREIGN KEY (shift_id) REFERENCES api.shifts(shift_id)
);
CREATE TABLE api.ai_risk_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid,
  shift_id uuid,
  risk_type text CHECK (risk_type = ANY (ARRAY['no_show_high'::text, 'gps_spoofing'::text, 'time_fraud'::text, 'credential_expire_soon'::text])),
  risk_score numeric,
  explanation text,
  flagged_at timestamp with time zone DEFAULT now(),
  resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  CONSTRAINT ai_risk_flags_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_risk_worker FOREIGN KEY (worker_id) REFERENCES api.workers(worker_id),
  CONSTRAINT fk_ai_risk_shift FOREIGN KEY (shift_id) REFERENCES api.shifts(shift_id),
  CONSTRAINT fk_ai_risk_resolved_by FOREIGN KEY (resolved_by) REFERENCES api.users(id)
);
CREATE TABLE api.ai_shift_forecasts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_id uuid NOT NULL,
  role text NOT NULL,
  forecast_date date NOT NULL,
  predicted_shifts_needed integer,
  confidence numeric,
  generated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_shift_forecasts_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_forecast_facility FOREIGN KEY (facility_id) REFERENCES api.facilities(id)
);
CREATE TABLE api.auth_trigger_logs (
  id bigint NOT NULL DEFAULT nextval('auth_trigger_logs_id_seq'::regclass),
  user_id uuid,
  detected_role text,
  message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT auth_trigger_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE api.compliance_docs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  employer_id uuid,
  file_url text NOT NULL,
  ai_scan_text text,
  ai_validation_status text,
  ai_validation_notes text,
  admin_verified boolean DEFAULT false,
  admin_notes text,
  expiration_date date,
  uploaded_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  doc_type text,
  status USER-DEFINED,
  ai_confidence_score numeric,
  ai_scan_timestamp timestamp with time zone,
  CONSTRAINT compliance_docs_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_docs_user_id_fkey FOREIGN KEY (user_id) REFERENCES api.users(id),
  CONSTRAINT compliance_docs_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES api.employers(employer_id)
);
CREATE TABLE api.employer_required_docs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_id uuid NOT NULL,
  state text NOT NULL,
  doc_type text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status USER-DEFINED,
  file_path text,
  CONSTRAINT employer_required_docs_pkey PRIMARY KEY (id),
  CONSTRAINT employer_required_docs_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES api.employers(employer_id)
);
CREATE TABLE api.employers (
  employer_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text,
  ein text,
  is_ein_verified boolean DEFAULT false,
  state text,
  address text,
  state_rules text,
  stripe_account_id text,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  stripe_status USER-DEFINED,
  docs_status USER-DEFINED,
  zip text,
  city text,
  name text,
  phone text,
  email text,
  employer_steps integer,
  compliance_status USER-DEFINED,
  user_id uuid UNIQUE,
  company_description text,
  company_logo_url text,
  rating double precision DEFAULT 0,
  total_shifts_posted integer DEFAULT 0,
  CONSTRAINT employers_pkey PRIMARY KEY (employer_id),
  CONSTRAINT employers_user_id_fkey FOREIGN KEY (user_id) REFERENCES api.users(id),
  CONSTRAINT fk_employers_user FOREIGN KEY (user_id) REFERENCES api.users(id)
);
CREATE TABLE api.facilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_id uuid NOT NULL,
  name text NOT NULL,
  address text,
  city text,
  state text,
  zip text,
  lat double precision,
  lng double precision,
  default_requirements jsonb DEFAULT '[]'::jsonb,
  default_physical_conditions jsonb DEFAULT '[]'::jsonb,
  default_social_interactions jsonb DEFAULT '[]'::jsonb,
  default_environment_conditions jsonb DEFAULT '[]'::jsonb,
  default_clothing_requirements jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT facilities_pkey PRIMARY KEY (id),
  CONSTRAINT fk_facilities_employer FOREIGN KEY (employer_id) REFERENCES api.employers(employer_id)
);
CREATE TABLE api.job_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  sector text CHECK (sector = ANY (ARRAY['Healthcare'::text, 'Non-Healthcare'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE api.notification (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  message text,
  type text,
  read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_pkey PRIMARY KEY (id)
);
CREATE TABLE api.payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_id uuid NOT NULL,
  stripe_payment_method_id text NOT NULL,
  type text CHECK (type = ANY (ARRAY['card'::text, 'bank_account'::text])),
  last4 text,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payment_methods_employer FOREIGN KEY (employer_id) REFERENCES api.employers(employer_id)
);
CREATE TABLE api.payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid NOT NULL,
  shift_id uuid NOT NULL,
  amount numeric NOT NULL,
  stripe_payout_id text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'paid'::text, 'failed'::text])),
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payouts_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payouts_worker FOREIGN KEY (worker_id) REFERENCES api.workers(worker_id),
  CONSTRAINT fk_payouts_shift FOREIGN KEY (shift_id) REFERENCES api.shifts(shift_id)
);
CREATE TABLE api.posted_shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  shift_date date NOT NULL,
  shift_time time without time zone NOT NULL,
  zone text NOT NULL,
  position text NOT NULL,
  quantity integer DEFAULT 1,
  hourly_wage numeric,
  status text DEFAULT 'open'::text,
  CONSTRAINT posted_shifts_pkey PRIMARY KEY (id)
);
CREATE TABLE api.requirement_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  icon_url text,
  est_time_min integer DEFAULT 0,
  sector_specific text CHECK (sector_specific = ANY (ARRAY['Healthcare'::text, 'Non-Healthcare'::text, 'Both'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requirement_types_pkey PRIMARY KEY (id)
);
CREATE TABLE api.shift_requirements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shift_id uuid NOT NULL,
  requirement_type_id uuid NOT NULL,
  description text,
  type text CHECK (type = ANY (ARRAY['verification'::text, 'onboarding'::text, 'credential'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shift_requirements_pkey PRIMARY KEY (id),
  CONSTRAINT fk_shift_requirements_shift FOREIGN KEY (shift_id) REFERENCES api.shifts(shift_id),
  CONSTRAINT fk_shift_requirements_type FOREIGN KEY (requirement_type_id) REFERENCES api.requirement_types(id)
);
CREATE TABLE api.shift_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_id uuid NOT NULL,
  template_name text NOT NULL,
  serialized_json jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shift_templates_pkey PRIMARY KEY (id),
  CONSTRAINT fk_shift_templates_employer FOREIGN KEY (employer_id) REFERENCES api.employers(employer_id)
);
CREATE TABLE api.shifts (
  shift_id uuid NOT NULL DEFAULT gen_random_uuid(),
  pay_rate numeric,
  total_pay numeric,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  duration_hours numeric,
  status text DEFAULT 'open'::text,
  pre_pay_amount numeric,
  huzly_fee numeric,
  stripe_intent text,
  completed timestamp with time zone,
  worker_id uuid,
  shift_date date NOT NULL,
  shift_time time without time zone NOT NULL,
  zone text,
  position text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  hourly_wage numeric NOT NULL,
  employer_id uuid NOT NULL,
  total_escrow numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  shift_title text,
  shift_description text,
  facility_id text,
  location_latlng text,
  required_credentials ARRAY,
  shift_notes text,
  category_id uuid,
  job_owner_id uuid,
  template_id uuid,
  estimated_fill_time interval,
  tasks_involved jsonb DEFAULT '[]'::jsonb,
  physical_conditions jsonb DEFAULT '[]'::jsonb,
  social_interactions jsonb DEFAULT '[]'::jsonb,
  environment_conditions jsonb DEFAULT '[]'::jsonb,
  additional_instructions text,
  clothing_requirements jsonb DEFAULT '{}'::jsonb,
  withdrawal_policy text DEFAULT 'Withdrawing less than 12 hours before start may result in penalties...'::text,
  sector text CHECK (sector = ANY (ARRAY['Healthcare'::text, 'Non-Healthcare'::text])),
  roles_array jsonb DEFAULT '[]'::jsonb,
  rate_per_hour numeric,
  estimated_hours numeric,
  payment_method_id uuid,
  stripe_authorization_id text,
  multi_day_dates jsonb DEFAULT '[]'::jsonb,
  ai_fill_probability numeric,
  ai_suggested_rate_increase numeric,
  CONSTRAINT shifts_pkey PRIMARY KEY (shift_id),
  CONSTRAINT shifts_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES api.employers(employer_id),
  CONSTRAINT fk_shifts_category FOREIGN KEY (category_id) REFERENCES api.job_categories(id),
  CONSTRAINT fk_shifts_job_owner FOREIGN KEY (job_owner_id) REFERENCES api.users(id),
  CONSTRAINT fk_shifts_template FOREIGN KEY (template_id) REFERENCES api.shift_templates(id),
  CONSTRAINT fk_shifts_payment_method FOREIGN KEY (payment_method_id) REFERENCES api.payment_methods(id)
);
CREATE TABLE api.state_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  state text NOT NULL,
  doc_type text NOT NULL,
  required boolean DEFAULT true,
  rules text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT state_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE api.todo (
  id uuid DEFAULT gen_random_uuid(),
  name text,
  address text,
  number text
);
CREATE TABLE api.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  password_hash text,
  verified boolean DEFAULT false,
  fully_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  notification_prefs text,
  last_login timestamp with time zone,
  role_users USER-DEFINED,
  employer_id uuid,
  worker_id uuid,
  role text DEFAULT 'user'::text CHECK (role = ANY (ARRAY['user'::text, 'employer'::text, 'worker'::text, 'admin'::text])),
  email text,
  name text,
  phone_number text,
  preferred_contact text,
  address text,
  lat numeric,
  long numeric,
  first text,
  last text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES api.employers(employer_id),
  CONSTRAINT users_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES api.workers(worker_id),
  CONSTRAINT api_users_auth_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE api.worker_shift_requirements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid NOT NULL,
  shift_requirement_id uuid NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'complete'::text, 'failed'::text])),
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT worker_shift_requirements_pkey PRIMARY KEY (id),
  CONSTRAINT fk_worker_shift_req_worker FOREIGN KEY (worker_id) REFERENCES api.workers(worker_id),
  CONSTRAINT fk_worker_shift_req_shift_req FOREIGN KEY (shift_requirement_id) REFERENCES api.shift_requirements(id)
);
CREATE TABLE api.workers (
  worker_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  address_validated text,
  city text,
  state text,
  zip text,
  lat double precision,
  lng double precision,
  roles text,
  rating double precision DEFAULT 0,
  total_shifts integer DEFAULT 0,
  no_shows integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  home_address jsonb DEFAULT '{}'::jsonb,
  phone text,
  email text,
  trust_score numeric,
  trust_updated_at timestamp with time zone,
  screen_step bigint,
  sector text,
  role_sector ARRAY,
  deleted_at timestamp without time zone,
  role text,
  CONSTRAINT workers_pkey PRIMARY KEY (worker_id)
);
CREATE TABLE api.workers_roles_ratings (
  rating_id text NOT NULL DEFAULT (gen_random_uuid())::text,
  role text,
  rating numeric,
  total_shifts integer,
  reviews text,
  last_updated timestamp with time zone DEFAULT now(),
  workers uuid,
  CONSTRAINT workers_roles_ratings_pkey PRIMARY KEY (rating_id)
);